### ISSUE TITLE
Type Shenanigans for endpoint.run in typescript

### ISSUE THREAD

**Issue by SnoFlak** [runpod/js-sdk#2]
While trying to pull the response data from endpoint.run, I kept running into some strange Typescript typing errors, that I think are possibly tied to the SDK `endpoint.run` returning a `Promise<string>`.

I'll also add that by no means am I an expert in Typescript, but, after running my code through GPT, browsing docs, no matter what I did I couldn't get my Typescript to not throw red squigglies at me, which in turn, wouldn't let me deploy on Vercel. 

```js
 const runpod = runpodSdk(runpodKey);
    const endpoint = runpod.endpoint(endpointId);
    if (!endpoint) {
        console.error("Endpoint is null. :) ");
        return;
    }
    try {
        const result = await endpoint.run({
            input: {
                text_prompt: prompts[0],
                motion_length: parseInt(length),
                seed: seed,
                cond_scale: parseInt(scale),
                user_id: userUID,
            },
        });

        const { id } = result;
        if (!id) {
            throw new Error("No ID returned from endpoint.run");
        }
```
*** ONLY RELEVANT BLOCK GIVEN ***

The issue I kept running into, is that result was labeled as type: string,  when, even if i console logged it, it would be an object. However, since Typescript insisted it was a string, i couldn't pull id from result, even though it was afterwards an object. I tried casting it to an Object, and would recieve the same issue, just that id isnt a valid part of Object. Making my own interface also would not work, because it thought result was a string, and a string could never break down into an object with both ID and STATUS. 

Again, im not an expert with Typescript, but after throwing the problems i was running into with GPT, as well as reading docs on typescript, I opted to just not use the SDK to populate my job, and instead just used fetch to call the Serverless Endpoint, and that worked just fine. 

Is it something im doing? I'm bringing it up because I noticed every other method from endpoint has its own class being passed in to its Promise, while run just has a string.

- My job was pushed to the endpoint and ran, but afterwards I wanted to grab the status of the job every couple seconds to update the users on their job. However, I couldn't grab the ID from the response the SDK was giving me to be able to make the status call.

**Comment by DireLines** [comment]
This looks like my typing error. I apologize, not sure how that happened. If I had to guess what led to this, I'd say I probably wrote the types intending to extract the id for you but then didn't in the actual call. I will update the type and publish an update shortly.

**Comment by SnoFlak** [comment]
Awesome!

I'm just glad I wasn't going crazy because of Typescript being Typescript. Thanks for the quick response! Ill keep an eye out for anything else, and move the code back over once its live.

**Comment by DireLines** [comment]
try pulling now, should be version 1.0.7
